version: "0"
services:
  web_collector:
    container_name: redSnooper
    hostname: redSnooper
    build: ./web-collector
    image: web-collector:latest
    restart: unless-stopped
    privileged: true
    dns:
    - 8.8.8.8
    - 9.9.9.9
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=1
    ports:
    - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
